import type { Row, RowWithRelationship } from '~/interfaces/ProductSell'

export const createDefaultProductSell = (overrides?: Partial<Row>): Row => ({
    id: 0,
    quantity: 0,
    type_id: 0,
    type: '',
    ean_gs1: null,
    model: null,
    description: null,
    category_id: null,
    syncecom: false,
    syncedecom: false,
    syncecominprogress: false,
    syncecomfailed: false,
    active: false,
    image: null,
    package_id: null,
    length: null,
    width: null,
    height: null,
    weight: null,
    gross_weight: null,
    weight_cubic: null,
    virtual_quantity: null,
    lead_time: null,
    featured_seal: null,
    release_seal: null,
    additional_seal: null,
    sync_comclick: false,
    sync_loja_do_tecnico: false,
    sync_viziotech: false,
    sell_price: '',
    promotion: false,
    liquidation: false,
    created_at: new Date(),
    updated_at: new Date(),
    // Sobrescreve os valores padrão com os valores fornecidos em 'overrides'
    ...(overrides || {})
})

export const createDefaultProductSellRS = (overrides?: Partial<RowWithRelationship>): RowWithRelationship => ({
    id: 0,
    quantity: 0,
    type_id: 0,
    type: '',
    ean_gs1: null,
    model: null,
    description: null,
    category_id: null,
    syncecom: false,
    syncedecom: false,
    syncecominprogress: false,
    syncecomfailed: false,
    active: false,
    image: null,
    package_id: null,
    length: null,
    width: null,
    height: null,
    weight: null,
    gross_weight: null,
    weight_cubic: null,
    virtual_quantity: null,
    lead_time: null,
    featured_seal: null,
    release_seal: null,
    additional_seal: null,
    sync_comclick: false,
    sync_loja_do_tecnico: false,
    sync_viziotech: false,
    sell_price: '',
    promotion: false,
    liquidation: false,
    created_at: new Date(),
    updated_at: new Date(),
    Family: {
        SellPreference: null,
        Products: [],
        id: 0,
        buy_preference_id: null,
        product_id: null,
        quantity: null,
        model: null,
        replace_cost: null,
        created_at: new Date(),
        updated_at: new Date(),
    },
    Kit: null,
    CategoryEcom: null,
    // Sobrescreve os valores padrão com os valores fornecidos em 'overrides'
    ...(overrides || {})

})