<script lang="ts" setup>
defineProps<{
  label: string;
}>();

const list = [
  "A ENVIAR",
  "A ENVIAR VINDI",
  "AGUARDANDO ETIQUETA TRANSP.",
  "AGUARDANDO MERCADO PAGO",
  "AGUARDANDO PAGAMENTO",
  "AGUARDANDO PAGAMENTO FRETE",
  "AGUARDANDO VINDI",
  "ARQUIVO RECEBIDO",
  "CANCELADO",
  "CANCELADO AUT",
  "CANCELADO DEV",
  "CANCELADO DEV AGILIZADA",
  "COLETA ADIADA",
  "COLETADO",
  "DEVOLUÇÃO TROCA",
  "DEVOLVER VALOR",
  "DEVOLVIDA AO REMETENTE",
  "EM SEPARAÇÃO",
  "EM TRANSFERÊNCIA",
  "EMBALADO",
  "EMBARCADO PARA: - RIA",
  "EMBARCADO PARA: - VIX",
  "EMBARQUE EM PONTO DE PASSAGEM - JDU",
  "EMBARQUE EM TRANSBORDO - SAO",
  "ENVIADO",
  "FATURADO",
  "FINALIZADO",
  "PROBLEMAS NA ENTREGA",
  "PROCESSO DE ENTREGA",
  "RECEBIDA E PROCESSADA NO CD",
];
</script>

<template>
  <UiCombobox :label="label" :items="list" clearable />
</template>
